### ISSUE TITLE
sqlmapapi

### ISSUE THREAD

**Issue by jax777** [imfht/ScanSql#1]
你没设置smart。。。肯定慢啊

**Comment by imfht** [comment]
感谢提醒! 正在重构代码,扫描器已出模样.本地跑了几次发现了不少问题,正在优化逻辑
测试加上smart之后一个url在20s内可以搞定

# 也在优化代码结构, 封装了类,优化了逻辑,尽量写得清楚点方便大家做二次开发!

## 感谢支持! 十分感谢!
